name: ActionDemo
on: [push]
jobs:
  echo1:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - run: echo "ok"
      - name: package
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: version
        run: java -version
      - name: package
        run: mvn package -DskipTest=true
      - name: Publish package
        run: mvn --batch-mode deploy -X
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
      - run: echo ${{ secrets.DEPLOYTOKEN }}